# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build kyria nice_nano_v2'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["kyria_rev2_left","kyria_rev2_right"]'
      kconfig: '["CONFIG_BT_CTLR_TX_PWR_PLUS_8=y"]'
